hollymovie/urls.py
import rest_framework
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

import accounts.views
import api
from api.views import *
from accounts.views import SignUpView
from viewer.admin import MovieAdmin
from viewer.models import *
from viewer.views import *


# zde budeme vytvářet cesty
urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello', hello),
    path('hello2/<s>', hello2),
    path('hello3/', hello3),
    path('hello4/', hello4),
    path('hello5/<s0>', hello5),

    path('', index, name='index'),

    path('accounts/login/', LoginView.as_view(), name='login'),    # vlastní view
    path('accounts/signup/', SignUpView.as_view(), name='signup'),  # vlastní view
    path('accounts/', include('django.contrib.auth.urls')),      # defaultní views pro přihlašování/odhlašování/změnu hesla...

    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),

    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),

    #path('movies/', movies, name='movies'),
    #path('movies/', MoviesView.as_view(), name='movies'),
    #path('movies/', MoviesTemplateView.as_view(), name='movies'),
    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie_detail/<pk>/', movie, name='movie'),

    #path('persons/', persons, name='persons'),
    #path('persons/', PersonsListView.as_view(), name='persons'),  # FIXME: zobrazit zvlášť herce a zvlášť režiséry
    path('persons/', actors, name='persons'),
    #path('person/create/', PersonFormView.as_view(), name='person_create'),
    path('person/create/', PersonCreateView.as_view(), name='person_create'),
    path('person/update/<pk>/', PersonUpdateView.as_view(), name='person_update'),
    path('person/delete/<pk>/', PersonDeleteView.as_view(), name='person_delete'),
    path('person/<pk>/', person, name='person'),  # FIXME

    path('rate_movie/', rate_movie, name='rate_movie'),
    path('add_comment', add_comment, name='add_comment'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', api.views.Movies.as_view()),
    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),
    path('api/persons/', api.views.PersonsList.as_view()),
    path('api/person/<pk>/', api.views.PersonDetail.as_view()),

    path('profiles/', accounts.views.ProfileListView.as_view(), name='profiles'),
    # path('profile/<pk>/', accounts.views.)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date

from django.db import models
from django.db.models import Model, CharField, IntegerField, TextField, DateField, ForeignKey, DO_NOTHING, \
    ManyToManyField, SET_NULL, DateTimeField, ImageField
from django.contrib.auth.models import User


# Create your models here.
class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self):
        return f"{self.name}"


class Genre(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)  # CharField => VARCHAR

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Person(Model):
    first_name = CharField(max_length=32, null=False, blank=False)
    last_name = CharField(max_length=32, null=False, blank=False)
    birth_date = DateField(null=True, blank=True)
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    # metoda pro výpočet věku
    def calculate_age(self):
        if self.birth_date:
            today = date.today()
            return (today.year - self.birth_date.year -
                    ((today.month, today.day) < (self.birth_date.month, self.birth_date.day)))
        return None


# TODO: upravit ve výpisu u filmu pořadí herců dle priorit
# Např. u Vykoupení z věznice Shawshank: Tim Robbins, Morgan Freeman, Bob Gunton


class Movie(Model):
    title_orig = CharField(max_length=64, null=False, blank=False)
    title_cz = CharField(max_length=64, null=True, blank=True)
    title_sk = CharField(max_length=64, null=True, blank=True)
    countries = ManyToManyField(Country, blank=True, related_name='movies_in_country')
    genres = ManyToManyField(Genre, blank=True, related_name='movies_of_genre')
    directors = ManyToManyField(Person, blank=False, related_name='directing_movie')
    actors = ManyToManyField(Person, blank=True, related_name='acting_in_movie')
    year = IntegerField(null=True, blank=True)
    video = CharField(max_length=128, null=True, blank=True)
    description = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig']

    def __str__(self):
        # pokud existuje český/slovenský název, tak ho zobrazit, jinak originální + do závorky zobrazit rok)
        # Příklad: Forrest Gump (1994)
        if self.title_cz:
            title = f"{self.title_cz}"
        else:
            title = f"{self.title_orig}"
        if self.year:
            title += f" ({self.year})"
        return title

    # TODO: metoda pro výpočet průměrného hodnocení


class Rating(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    rating = IntegerField(null=False, blank=False)

    def __str__(self):
        return f"{self.movie}: {self.rating} by {self.user}"


class Comment(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    comment = TextField(null=False, blank=False)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.movie} ({self.user}): {self.comment[:50]}"


class Image(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    #url = CharField(max_length=128, null=False, blank=False)
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)  #, height_field=None, width_field=None, max_length=500)
    description = TextField()

    def __str__(self):
        return f"{self.movie}: {self.description[:50]}"

viewer/views.py
from datetime import datetime
from logging import getLogger

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Avg
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView
from django_addanother.views import CreatePopupMixin
from django_addanother.widgets import AddAnotherWidgetWrapper

from viewer.models import *
from django.forms import Form, ModelChoiceField, Textarea, IntegerField, CharField, ModelMultipleChoiceField, \
    CheckboxSelectMultiple, ModelForm, DateField, SelectDateWidget, DateInput, SelectMultiple

LOGGER = getLogger()


# Create your views here.
def hello(request):
    return HttpResponse("Hello, World!")


def hello2(request, s):
    return HttpResponse(f"Hello, {s} world!")


def hello3(request):
    s = request.GET.get('s', '')
    return HttpResponse(f"Hello, {s} world!")


def hello4(request):
    return render(request, template_name='hello.html')


def hello5(request, s0):
    s1 = request.GET.get('s1', '')
    context = {'adjectives': [s0, s1, 'beautiful', 'wonderful']}
    return render(
        request,
        template_name='hello5.html',
        context=context
    )


def index(request):
    return render(request, 'index.html')


class GenreModelForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'

    def clean_name(self):
        cleaned_data = super().clean()
        name = cleaned_data['name'].strip().capitalize()
        return name


class GenreCreateView(LoginRequiredMixin, CreateView):
    template_name = 'movie_create.html'  # TODO genre_create.html
    form_class = GenreModelForm
    success_url = reverse_lazy('index')


class GenreUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'genre_create.html'
    model = Genre
    form_class = GenreModelForm
    success_url = reverse_lazy('index')


class GenreDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'person_confirm_delete.html'  # TODO genre_confirm_delete.html
    model = Genre
    success_url = reverse_lazy('index')


class CountryModelForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

    def clean_name(self):
        cleaned_data = super().clean()
        name = cleaned_data['name'].strip().capitalize()
        return name


class CountryCreateView(LoginRequiredMixin, CreatePopupMixin, CreateView):
    template_name = 'movie_create.html'  # TODO country_create.html
    form_class = CountryModelForm
    success_url = reverse_lazy('index')


class CountryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'country_create.html'
    model = Country
    form_class = CountryModelForm
    success_url = reverse_lazy('index')


class CountryDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'person_confirm_delete.html'  # TODO country_confirm_delete.html
    model = Country
    success_url = reverse_lazy('index')


def movies(request):
    g = request.GET.get('genre', '')
    c = request.GET.get('country', '')
    genres = Genre.objects.all()
    if g != '' and c != '':
        g = int(g)
        c = int(c)
        if Genre.objects.filter(id=g).exists() and Country.objects.filter(id=c).exists():
            genre = Genre.objects.get(id=g)
            country = Country.objects.get(id=c)
            movie_list = Movie.objects.filter(genres=genre, countries=country)
            context = {'movies': movie_list, 'genres': genres, 'filtered_by': f'podle žánru {genre} a země {country}.'}
            return render(request, 'movies.html', context)
    if g != '':
        g = int(g)
        if Genre.objects.filter(id=g).exists():
            genre = Genre.objects.get(id=g)
            context = {'movies': genre.movies_of_genre.all(), 'genres': genres, 'filtered_by': f'podle žánru {genre}'}
            return render(request, 'movies.html', context)
        else:
            context = {'movies': [], 'genres': genres, 'filtered_by': ''}
            return render(request, 'movies.html', context)

    if c != '':
        c = int(c)
        if Country.objects.filter(id=c).exists():
            country = Country.objects.get(id=c)
            context = {'movies': country.movies_in_country.all(), 'genres': genres,
                       'filtered_by': f'podle země {country}'}
            return render(request, 'movies.html', context)
        else:
            context = {'movies': [], 'genres': genres, 'filtered_by': ''}
            return render(request, 'movies.html', context)

    movies_list = Movie.objects.all()
    genre_list = Genre.objects.all()
    context = {'movies': movies_list, 'genres': genre_list, 'filtered_by': ''}
    return render(request, 'movies.html', context)


def movies_by_genre(request, pk):
    genre_movies = Genre.objects.get(id=pk)
    genre_list = Genre.objects.all()
    context = {'movies': genre_movies.movies_of_genre.all(), 'genres': genre_list}
    return render(request, 'movies.html', context)


def movies_by_country(request, pk):
    country_movies = Country.objects.get(id=pk)
    country_list = Country.objects.all()
    genre_list = Genre.objects.all()
    context = {'movies': country_movies.movies_in_country.all(), 'countries': country_list, 'genres': genre_list}
    return render(request, 'movies.html', context)


class MoviesView(View):
    def get(self, request):
        movies_list = Movie.objects.all()
        context = {'movies': movies_list}
        return render(request, 'movies.html', context)


class MoviesTemplateView(TemplateView):
    template_name = 'movies.html'
    extra_context = {'movies': Movie.objects.all()}


class MoviesListView(ListView):
    template_name = 'movies2.html'
    model = Movie
    paginate_by = 5


def movie(request, pk):
    try:
        movie_obj = Movie.objects.get(id=pk)
    except:
        return render(request, 'index.html')  # TODO: vypsat na vyrenderované stránce chybu

    # spočítat průměrné hodnocení filmu
    avg_rating = None
    if Rating.objects.filter(movie=movie_obj).count() > 0:
        avg_rating = Rating.objects.filter(movie=movie_obj).aggregate(Avg('rating'))

    # hodnocení od daného uživatele
    user = request.user
    user_rating = None
    if request.user.is_authenticated:
        if Rating.objects.filter(movie=movie_obj, user=user).count() > 0:
            user_rating = Rating.objects.get(movie=movie_obj, user=user)

    # komentáře k filmu
    comments = Comment.objects.filter(movie=movie_obj).order_by('-created')

    # obrázky k filmu
    images = Image.objects.filter(movie=movie_obj)

    context = {'movie': movie_obj, 'avg_rating': avg_rating,
               'user_rating': user_rating, 'comments': comments, 'images': images}
    return render(request, 'movie.html', context)


class MovieForm(Form):
    title_orig = CharField(max_length=64)
    title_cz = CharField(max_length=64, required=False)
    title_sk = CharField(max_length=64, required=False)
    countries = ModelMultipleChoiceField(queryset=Country.objects)
    genres = ModelMultipleChoiceField(queryset=Genre.objects, widget=CheckboxSelectMultiple)
    directors = ModelMultipleChoiceField(queryset=Person.objects)
    actors = ModelMultipleChoiceField(queryset=Person.objects)
    year = IntegerField(min_value=1900, max_value=datetime.now().year + 3)
    video = CharField(max_length=128, required=False)
    description = CharField(widget=Textarea, required=False)

    def clean_title_orig(self):
        initial_form = super().clean()
        initial = initial_form['title_orig'].strip()
        return initial.capitalize()

    def clean(self):
        return super().clean()


class MovieModelForm(LoginRequiredMixin, ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

        widgets = {
            'countries': AddAnotherWidgetWrapper(
                SelectMultiple,
                reverse_lazy('country_create')
            )
        }

        labels = {
            'title_orig': 'Originální název'
        }

        help_texts = {
            'title_orig': 'Zadejte originální název'
        }

        error_messages = {
            'title_orig': {
                'max_length': 'Zadaný název je příliš dlouhý'
            }
        }

    def clean_title_orig(self):
        initial_form = super().clean()
        initial = initial_form['title_orig'].strip()
        return initial.capitalize()

    def clean(self):
        return super().clean()


class MovieFormView(LoginRequiredMixin, FormView):
    template_name = 'movie_create.html'
    form_class = MovieForm
    success_url = reverse_lazy('movie_create')

    def form_valid(self, form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        new_movie = Movie.objects.create(
            title_orig=cleaned_data['title_orig'],
            title_cz=cleaned_data['title_cz'],
            title_sk=cleaned_data['title_sk'],
            # countries=cleaned_data['countries'],
            # genres=cleaned_data['genres'],
            # directors=cleaned_data['directors'],
            # actors=cleaned_data['actors'],
            year=cleaned_data['year'],
            video=cleaned_data['video'],
            description=cleaned_data['description']
        )
        new_movie.countries.set(cleaned_data['countries'])
        new_movie.genres.set(cleaned_data['genres'])
        new_movie.directors.set(cleaned_data['directors'])
        new_movie.actors.set(cleaned_data['actors'])
        new_movie.save()
        return result

    def form_invalid(self, form):
        print('User provided invalid data.')
        LOGGER.warning('User provided invalid data.')
        return super().form_invalid(form)


class MovieCreateView(PermissionRequiredMixin, CreateView):

viewer/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello to our movie database</h1>
</body>
</html>

viewer/templates/hello5.html
<!DOCTYPE html>
<html>
  <body>
    <h1>Welcome to HollyMovies!</h1>
    {% for adjective in adjectives %}
      {% if adjective != 'cruel' %}
        <p>This is a {{ adjective }} world...</p>
      {% endif %}
    {% endfor %}
  </body>
</html>

viewer/templates/index.html
{% extends "base.html" %}

{% block content %}

<h2>Welcome to our outstanding page about the best of Cinematography.<span id="date-time"></span></h2>
<div class="movie-box" id="movieBox">
    <div class="arrow left" onclick="showPreviousMovie()">&#9665;</div>
    <div class="movie-item" onclick="toggleVideo()">
        <div class="image-container">
            <img class="movie-image" src="">
        </div>
    </div>
    <div class="arrow right" onclick="showNextMovie()">&#9655;</div>
    <div class="video-container">
        <video id="movieVideo" width="100%" height="100%" controls></video>
    </div>
</div>

{% endblock %}

viewer/templates/movie.html
{% extends "base.html" %}

{% block title %}
{{ movie.title_orig }}
{% endblock %}

{% block content %}
<h1>{{ movie.title_orig|upper }}</h1>
<div class="movie-details">
    <div class="images">
        {% for image in images %}
        <div class="image-container"><img src="{{ image.image.url }}" width="150px"></div>
        {% endfor %}
    </div>

    <div class="movie-title-orig">Originální název: {{ movie.title_orig }}</div>
    <div class="movie-title-cz">Český název: {{ movie.title_cz }}</div>
    <div class="movie-title-sk">Slovenský název: {{ movie.title_sk }}</div>
    <div class="movie-year">Rok: {{ movie.year }}</div>

    <div class="movie-countries">Země:
        {% for country in movie.countries.all %}
            {{ country }}
        {% endfor %}
    </div>

    <div class="movie-genres">Žánry:
        {% for genre in movie.genres.all %}
            {{ genre }}
        {% endfor %}
    </div>

    <span class="movie-directors">Režie:
        {% for director in movie.directors.all %}
            <span class="movie-director"><a href="{% url 'person' director.id %}">{{ director }}</a></span>
        {% endfor %}
    </span>

    <span class="movie-actors">Hrají:
        {% for actor in movie.actors.all %}
            <span class="movie-actor"><a href="{% url 'person' actor.id %}">{{ actor }}</a></span>
        {% empty %}
            Nikdo nehraje.
        {% endfor %}
    </span>

    <div class="movie-description">Popis: {{ movie.description }}</div>
    <div class="movie-video"><a href="{{ movie.video }}">Video</a></div>
    <div class="movie-avg-rating">Průměrné hodnocení:
        {% if avg_rating %}
            {{ avg_rating.rating__avg|floatformat:"0" }}
        {% else %}
            Dosud nehodnoceno
        {% endif %}
    </div>
    {% if request.user.is_authenticated %}
        {% if user_rating %}
            Vaše hodnocení je: {{ user_rating.rating }}
        {% endif %}
        <form method="post" action="{% url 'rate_movie' %}">
            {% csrf_token %}
            <label for="rating">Hodnocení filmu (0-100):</label>
            <input type="number" id="rating" name="rating" min="0" max="100">
            <input type="hidden" name="movie_id" value="{{ movie.id }}">
            <input type="submit">
        </form>

        {% if perms.viewer.change_movie %}
            <a href="{% url 'movie_update' movie.id %}"><button>Upravit</button></a>
        {% endif %}
        {% if perms.viewer.delete_movie %}
            <a href="{% url 'movie_delete' movie.id %}"><button>Smazat</button></a>
        {% endif %}
    {% endif %}

    {% if request.user.is_authenticated %}
    <form action="{% url 'add_comment' %}" method="post">
        {% csrf_token %}
        <label for="rating">Pridat komentar:</label>
        <div>
            <textarea name="comment" cols="100" rows="5"></textarea>
        </div>
        <input type="hidden" name="movie_id" value="{{ movie.id }}">
        <input type="submit" value="Odoslat komentar">
    </form>
    {% endif %}

    <h3>Komentáře k filmu:</h3>
    {% for comment in comments %}
        <p>
        {{ comment.comment }}
        <h6><strong>{{ comment.user }}</strong></h6>
         <h6>{{ comment.created }}</h6>
        </p>
        <hr>
    {% empty %}
        Dosud žádný komentář.
    {% endfor %}

</div>
{% endblock %}

viewer/templates/movie_create.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
        <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
        {{ form.media }}
    </table>
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
<h1>Žánry</h1>
<ul>
    {% for genre in genres %}
    <li><a href="{% url 'genre' genre.id %}">{{genre}}</a> </li>
    {% endfor %}
</ul>
<h1>Seznam filmů {{ filtered_by }} </h1>
<ul>
    {% for movie in movies %}
    <li><a href="{% url 'movie' movie.id %}">{{movie}}</a> </li>
    {% endfor %}
</ul>
<a href="{% url 'movie_create' %}"><button>Přidat film</button></a>
{% endblock %}

viewer/templates/movies2.html
{% extends "base.html" %}

{% block content %}
    <h1>Seznam filmů</h1>
    <ul>
        {% for movie in object_list %}
            <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a></li>
        {% endfor %}
    </ul>

    <!-- pagination v1: Stránka 1 z 3 Následující -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                Stránka {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    <!-- pagination v2: Předchozí 1 2 3 Následující -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="current-page">
                            <a href="?page={{ i }}">{{ i }}</a>
                        </span>
                    {% else %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    <!-- pagination v3:  Předchozí 1 ... 3 4 5 6 7 ... 11 Následující  -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="current-page">
                            <a href="?page={{ i }}">{{ i }}</a>
                        </span>
                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    {% if page_obj.number < page_obj.paginator.num_pages|add:'-4' %}
                        <span>...</span>
                    {% endif %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    {% if perms.viewer.add_movie %}
        <a href="{% url 'movie_create' %}"><button>Přidat film</button></a>
    {% endif %}
{% endblock %}

viewer/templates/p400.html
{% extends "base.html" %}

{% block title %} Neoprávněný přístup {% endblock %}


{% block content %}
<h1>Neexistující stránka</h1>
{% endblock %}

viewer/templates/person.html
{% extends "base.html" %}

{% block content %}
<h1>{{ person }}</h1>
<div class="person-details">
    <div class="person-first-name">Jméno: {{ person.first_name }}</div>
    <div class="person-last-name">Příjmení: {{ person.last_name }}</div>
    <div class="person-birth-date">Datum narození: {{ person.birth_date }} (věk: {{person.calculate_age}})</div>
    <div class="person-acting-in-movies">Herec:
        {% for movie in person.acting_in_movie.all %}
            <span class="person-acting-in-movie"><a href="{% url 'movie' movie.id %}">{{ movie }}</a></span>
        {% empty %}
            Nehrál v žádném filmu
        {% endfor %}
    </div>
    <div class="person-directing-movies">Režisér:
        {% for movie in person.directing_movie.all %}
            <span class="person-directing-movie"><a href="{% url 'movie' movie.id %}">{{ movie }}</a></span>
        {% empty %}
            Nerežíroval žádný film
        {% endfor %}
    </div>
    <div class="person-biography">Biografie: {{ person.biography }}</div>
    {% if perms.viewer.change_person %}
        <a href="{% url 'person_update' person.id %}"><button>Upravit</button></a>
    {% endif %}
    {% if perms.viewer.delete_person %}
        <a href="{% url 'person_delete' person.id %}"><button>Smazat</button></a>
    {% endif %}
</div>
{% endblock %}

viewer/templates/person_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
      Opravdu chcete smazat záznam pro: "{{ object }}" z databáze?
    </p>
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/person_create.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/persons.html
{% extends "base.html" %}

{% block content %}
<h1>Seznam lidí</h1>
<ul>
    {% for person in persons %}
        <li><a href="{% url 'person' person.id %}">{{ person }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/persons2.html
{% extends "base.html" %}

{% block content %}
<div class="actors-list">
    <h1>Seznam herců</h1>
    <ul>
        {% for actor in actors %}
            <li><a href="{% url 'person' actor.id %}">{{actor}} ({{actor.acting_in_movie.count}})</a> </li>
        {% endfor %}
    </ul>
</div>
<div class="directors-list">
    <h1>Seznam režisérů</h1>
    <ul>
        {% for director in directors %}
            <li><a href="{% url 'person' director.id %}">{{director}} ({{director.directing_movie.count}})</a> </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}