hollymovie/urls.py
import rest_framework
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

import accounts.views
import api
from api.views import *
from accounts.views import SignUpView
from viewer.admin import MovieAdmin
from viewer.models import *
from viewer.views import *


# zde budeme vytvářet cesty
urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello', hello),
    path('hello2/<s>', hello2),
    path('hello3/', hello3),
    path('hello4/', hello4),
    path('hello5/<s0>', hello5),

    path('', index, name='index'),

    path('accounts/login/', LoginView.as_view(), name='login'),    # vlastní view
    path('accounts/signup/', SignUpView.as_view(), name='signup'),  # vlastní view
    path('accounts/', include('django.contrib.auth.urls')),      # defaultní views pro přihlašování/odhlašování/změnu hesla...

    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),

    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),

    #path('movies/', movies, name='movies'),
    #path('movies/', MoviesView.as_view(), name='movies'),
    #path('movies/', MoviesTemplateView.as_view(), name='movies'),
    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie_detail/<pk>/', movie, name='movie'),

    #path('persons/', persons, name='persons'),
    #path('persons/', PersonsListView.as_view(), name='persons'),  # FIXME: zobrazit zvlášť herce a zvlášť režiséry
    path('persons/', actors, name='persons'),
    #path('person/create/', PersonFormView.as_view(), name='person_create'),
    path('person/create/', PersonCreateView.as_view(), name='person_create'),
    path('person/update/<pk>/', PersonUpdateView.as_view(), name='person_update'),
    path('person/delete/<pk>/', PersonDeleteView.as_view(), name='person_delete'),
    path('person/<pk>/', person, name='person'),  # FIXME

    path('rate_movie/', rate_movie, name='rate_movie'),
    path('add_comment', add_comment, name='add_comment'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', api.views.Movies.as_view()),
    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),
    path('api/persons/', api.views.PersonsList.as_view()),
    path('api/person/<pk>/', api.views.PersonDetail.as_view()),

    path('profiles/', accounts.views.ProfileListView.as_view(), name='profiles'),
    # path('profile/<pk>/', accounts.views.)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import DateField, TextField, Model, OneToOneField, CASCADE


# Create your models here.
class Profile(Model):
    user = OneToOneField(User, on_delete=CASCADE)
    birth_date = DateField(null=True, blank=True)
    biography = TextField(null=True, blank=True)
    #student
    #employee

    def __str__(self):
        return f"{self.user}"

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView, DetailView

from accounts.models import Profile


# Create your views here.
class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        #fields = '__all__'
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('index')
    template_name = 'signup.html'


# TODO: ProfileCreate
# TODO: ProfileUpdate
# TODO: ProfileDelete

class ProfileListView(ListView):
    template_name = 'profiles.html'
    model = Profile
    paginate_by = 10
    context_object_name = 'profiles'


class ProfileDetailView(DetailView):
    pass

accounts/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ profile }}</h1>
<div class="profile-details">
    <div class="profile-first-name">Jméno: {{ profile.first_name }}</div>
    <div class="profile-last-name">Příjmení: {{ profile.last_name }}</div>
    <div class="profile-birth-date">Datum narození: {{ profile.birth_date }} (věk: {{profile.calculate_age}})</div>
    <div class="profile-biography">Biografie: {{ profile.biography }}</div>
    {% if perms.accounts.change_profile %}
        <a href="{% url 'profile_update' profile.id %}"><button>Upravit</button></a>
    {% endif %}
    {% if perms.accounts.delete_profile %}
        <a href="{% url 'profile_delete' profile.id %}"><button>Smazat</button></a>
    {% endif %}
</div>
{% endblock %}

accounts/templates/profiles.html
{% extends "base.html" %}

{% block content %}
<div class="actors-list">
    <h1>Seznam profilů</h1>
    <ul>
        {% for profile in profiles %}
            <li>
                    {{ profile }}
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}

{% block content %}

<div class="login-form">
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="id-submit">Sign up</button>
    </form>

</div>

{% endblock %}