hollymovie/urls.py
import rest_framework
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

import accounts.views
import api
from api.views import *
from accounts.views import SignUpView
from viewer.admin import MovieAdmin
from viewer.models import *
from viewer.views import *


# zde budeme vytvářet cesty
urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello', hello),
    path('hello2/<s>', hello2),
    path('hello3/', hello3),
    path('hello4/', hello4),
    path('hello5/<s0>', hello5),

    path('', index, name='index'),

    path('accounts/login/', LoginView.as_view(), name='login'),    # vlastní view
    path('accounts/signup/', SignUpView.as_view(), name='signup'),  # vlastní view
    path('accounts/', include('django.contrib.auth.urls')),      # defaultní views pro přihlašování/odhlašování/změnu hesla...

    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),

    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),

    #path('movies/', movies, name='movies'),
    #path('movies/', MoviesView.as_view(), name='movies'),
    #path('movies/', MoviesTemplateView.as_view(), name='movies'),
    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie_detail/<pk>/', movie, name='movie'),

    #path('persons/', persons, name='persons'),
    #path('persons/', PersonsListView.as_view(), name='persons'),  # FIXME: zobrazit zvlášť herce a zvlášť režiséry
    path('persons/', actors, name='persons'),
    #path('person/create/', PersonFormView.as_view(), name='person_create'),
    path('person/create/', PersonCreateView.as_view(), name='person_create'),
    path('person/update/<pk>/', PersonUpdateView.as_view(), name='person_update'),
    path('person/delete/<pk>/', PersonDeleteView.as_view(), name='person_delete'),
    path('person/<pk>/', person, name='person'),  # FIXME

    path('rate_movie/', rate_movie, name='rate_movie'),
    path('add_comment', add_comment, name='add_comment'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', api.views.Movies.as_view()),
    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),
    path('api/persons/', api.views.PersonsList.as_view()),
    path('api/person/<pk>/', api.views.PersonDetail.as_view()),

    path('profiles/', accounts.views.ProfileListView.as_view(), name='profiles'),
    # path('profile/<pk>/', accounts.views.)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date

from django.db import models
from django.db.models import Model, CharField, IntegerField, TextField, DateField, ForeignKey, DO_NOTHING, \
    ManyToManyField, SET_NULL, DateTimeField, ImageField
from django.contrib.auth.models import User


# Create your models here.
class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self):
        return f"{self.name}"


class Genre(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)  # CharField => VARCHAR

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Person(Model):
    first_name = CharField(max_length=32, null=False, blank=False)
    last_name = CharField(max_length=32, null=False, blank=False)
    birth_date = DateField(null=True, blank=True)
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    # metoda pro výpočet věku
    def calculate_age(self):
        if self.birth_date:
            today = date.today()
            return (today.year - self.birth_date.year -
                    ((today.month, today.day) < (self.birth_date.month, self.birth_date.day)))
        return None


# TODO: upravit ve výpisu u filmu pořadí herců dle priorit
# Např. u Vykoupení z věznice Shawshank: Tim Robbins, Morgan Freeman, Bob Gunton


class Movie(Model):
    title_orig = CharField(max_length=64, null=False, blank=False)
    title_cz = CharField(max_length=64, null=True, blank=True)
    title_sk = CharField(max_length=64, null=True, blank=True)
    countries = ManyToManyField(Country, blank=True, related_name='movies_in_country')
    genres = ManyToManyField(Genre, blank=True, related_name='movies_of_genre')
    directors = ManyToManyField(Person, blank=False, related_name='directing_movie')
    actors = ManyToManyField(Person, blank=True, related_name='acting_in_movie')
    year = IntegerField(null=True, blank=True)
    video = CharField(max_length=128, null=True, blank=True)
    description = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig']

    def __str__(self):
        # pokud existuje český/slovenský název, tak ho zobrazit, jinak originální + do závorky zobrazit rok)
        # Příklad: Forrest Gump (1994)
        if self.title_cz:
            title = f"{self.title_cz}"
        else:
            title = f"{self.title_orig}"
        if self.year:
            title += f" ({self.year})"
        return title

    # TODO: metoda pro výpočet průměrného hodnocení


class Rating(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    rating = IntegerField(null=False, blank=False)

    def __str__(self):
        return f"{self.movie}: {self.rating} by {self.user}"


class Comment(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    comment = TextField(null=False, blank=False)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.movie} ({self.user}): {self.comment[:50]}"


class Image(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    #url = CharField(max_length=128, null=False, blank=False)
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)  #, height_field=None, width_field=None, max_length=500)
    description = TextField()

    def __str__(self):
        return f"{self.movie}: {self.description[:50]}"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'viewer/styless.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% if not view.is_popup %}
        <header class="headContainer">
            <img class="headContainer-part" alt="Yoda1" src="{% static 'viewer/images/HD-wallpaper-jedi-yoda-star-wars-lightsbar-black-background-dark-theme.jpg' %}">
            <a href="{% url 'index' %}"  class="headContainer-center"><h1>Endless Movie database</h1></a>
            <img class="headContainer-part" alt="Yoda2" src="{% static 'viewer/images/wp7248743.webp' %}">
        </header>
        <nav class="navContainer">
            {% if request.user.is_authenticated %}
                Přihlášen jako: {{ request.user.username }}
                <a href="{% url 'logout' %}"><button id="button-logout">Logout</button></a>
            {% else %}
                <a href="{% url 'signup' %}"><button id="button-signup">Register</button></a>
                <a href="{% url 'login' %}"><button id="button-login">Login</button></a>
            {% endif %}
            {% if request.user.is_superuser %}
                <a href="/admin/"><button>Admin</button></a>
            {% endif %}
        </nav>
        <nav class="navContainer2">
            <a href="News.html"><button>News in Cinemas</button></a>
            <a href="NewsOnDVD.html"><button>News on DVD</button></a>
            <a href="{% url 'movies' %}"><button>Filmy</button></a>
            <a href="{% url 'persons' %}"><button>Herci a režiséři</button></a>
            {% if request.user.is_authenticated %}
                {% if perms.viewer.add_movie %}
                    <a href="{% url 'movie_create' %}"><button>Přidat film</button></a>
                {% endif %}
                {% if perms.viewer.add_person %}
                    <a href="{% url 'person_create' %}"><button>Přidat osobu</button></a>
                {% endif %}
            {% endif %}
        </nav>
    {% endif %}
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>Copyright Created by Marcel Jurčák 2.12.2023</footer>
    <script src="{% static 'viewer/script.js' %} "></script>
</body>
</html>